[project]
name = "advent-of-code"
version = "0.1.0"
description = "Some advent of code solutions."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.8.1",
]

[tool.ruff]
line-length = 125
